### ISSUE TITLE
Implement product description synchronization from OpenCart to Electra

### ISSUE THREAD

**Issue by iliyan-velichkov** [codbex/codbex-electra#23]
OpenCart table `oc_product_description` should be replicated as well to be able to replicate all products and corresponding attributes to eMAG.
In addition, the table data could be visualized in the Electra Products UI.

**Comment by iliyan-velichkov** [comment]
PR: https://github.com/codbex/codbex-electra/pull/73

**Comment by ThuF** [comment]
@iliyan-velichkov I guess we should close this issue, as the PR was merged?
