### ISSUE TITLE
Research whether the Electra is vulnerable for SQL injection on inbound synchronization

### ISSUE THREAD

**Issue by iliyan-velichkov** [codbex/codbex-electra#42]
Check whether the Electra is vulnerable for SQL injection.
For example, try to insert some malicious data into OpenCart DB directly or via the UI and check whether it will affect the Electra DB during the synchronization execution.

**Comment by iliyan-velichkov** [comment]
will be mitigated with the fix for https://github.com/codbex/codbex-electra/issues/41

**Comment by iliyan-velichkov** [comment]
fixed with: https://github.com/codbex/codbex-electra/pull/94

**Comment by ThuF** [comment]
@iliyan-velichkov should we close this issue?
