### ISSUE TITLE
Add support for multiple stores (OpenCarts and eMAGs)

### ISSUE THREAD

**Issue by iliyan-velichkov** [codbex/codbex-electra#92]
We should be able to configure multiple stores (more than one OpenCart and eMAG stores).
The synchronization should work for all stores.
You should be able to configure which products will be available in the stores.

The change requires to change the direction of the current synchronizations for all entities.
All camels and listeners must be rewritten.

**Comment by iliyan-velichkov** [comment]
reference entity
![image](https://github.com/codbex/codbex-electra/assets/5058839/e3449ab4-b3f7-4f18-bf83-14c26c5ada27)

**Comment by iliyan-velichkov** [comment]
WIP PR: https://github.com/codbex/codbex-electra/pull/94

**Comment by iliyan-velichkov** [comment]
store model updated:
![image](https://github.com/codbex/codbex-electra/assets/5058839/4de07d29-17da-48f4-bbee-2fef421837d6)

**Comment by ThuF** [comment]
@iliyan-velichkov I guess we should close this issue, as the PR was merged?
